server {
    listen 80;
    server_name admin.micasachurch.co;
    root /home/srdejo/apps/micasachurch/frontend-admin;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
